-- Crear la bd
CREATE DATABASE rehabilitacion_fisica;
\c rehabilitacion_fisica;
-- Entidades maestros
CREATE TABLE pacientes (
    id_paciente INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    apellido_paterno VARCHAR(50) NOT NULL,
    apellido_materno VARCHAR(50) NOT NULL,
    fecha_nacimiento DATE NOT NULL,
    sexo VARCHAR(10) NOT NULL CHECK (sexo IN ('MASCULINO','FEMENINO','OTRO')),
    telefono VARCHAR(15),
    correo VARCHAR(100) UNIQUE,
    direccion VARCHAR(150),
    diagnostico_principal VARCHAR(100) NOT NULL,
    antecedentes_medicos TEXT
);

CREATE TABLE terapeutas (
    id_terapeuta INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    apellido_paterno VARCHAR(50) NOT NULL,
    apellido_materno VARCHAR(50) NOT NULL,
    especialidad VARCHAR(100) NOT NULL,
    telefono VARCHAR(15),
    correo VARCHAR(100) UNIQUE,
    observaciones TEXT
);

CREATE TABLE ejercicios (
    id_ejercicio INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_ejercicio VARCHAR(100) NOT NULL,
    descripcion TEXT NOT NULL,
    tipo_ejercicio VARCHAR(50) NOT NULL,
    nivel_dificultad VARCHAR(20) NOT NULL CHECK (nivel_dificultad IN ('BAJO','MEDIO','ALTO'))
);

CREATE TABLE vehiculos (
    id_vehiculo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo VARCHAR(50) NOT NULL,
    descripcion TEXT NOT NULL,
    estado VARCHAR(20) NOT NULL CHECK (estado IN ('DISPONIBLE','EN_USO','MANTENIMIENTO'))
);

CREATE TABLE dispositivos_nfc (
    id_dispositivo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_dispositivo VARCHAR(50) NOT NULL,
    ubicacion VARCHAR(100) NOT NULL,
    estado VARCHAR(20) NOT NULL CHECK (estado IN ('ACTIVO','INACTIVO','MANTENIMIENTO')),
    descripcion TEXT
);

CREATE TABLE beacons (
    id_beacon INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    area VARCHAR(50) NOT NULL,
    habitacion VARCHAR(50) NOT NULL,
    estado_beacon VARCHAR(20) NOT NULL CHECK (estado_beacon IN ('ACTIVO','INACTIVO'))
);
-- Entidades transaccionales
CREATE TABLE sesiones (
    id_sesion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha DATE NOT NULL,
    hora_inicio TIME NOT NULL,
    hora_fin TIME NOT NULL,
    tipo_sesion VARCHAR(50) NOT NULL,
    observaciones_clinicas TEXT,
    asistencia BOOLEAN NOT NULL,
    metodo_registro VARCHAR(50) NOT NULL,
    CONSTRAINT check_horas CHECK (hora_fin > hora_inicio)
);

CREATE TABLE evaluaciones_progreso (
    id_evaluacion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha DATE NOT NULL,
    tipo_evaluacion VARCHAR(50) NOT NULL,
    nivel_movilidad INTEGER NOT NULL CHECK (nivel_movilidad BETWEEN 0 AND 10),
    nivel_dolor INTEGER NOT NULL CHECK (nivel_dolor BETWEEN 0 AND 10),
    resistencia INTEGER NOT NULL CHECK (resistencia BETWEEN 0 AND 10),
    progreso_observado TEXT,
    recomendaciones TEXT,
    ajustes_plan TEXT
);
-- Tablas multivaluadas
CREATE TABLE paciente_alergia (
    id_paciente INTEGER NOT NULL,
    alergia VARCHAR(100) NOT NULL,
    PRIMARY KEY (id_paciente, alergia),
    FOREIGN KEY (id_paciente) REFERENCES pacientes(id_paciente)
);

CREATE TABLE paciente_lesion (
    id_paciente INTEGER NOT NULL,
    lesion_previa VARCHAR(100) NOT NULL,
    PRIMARY KEY (id_paciente, lesion_previa),
    FOREIGN KEY (id_paciente) REFERENCES pacientes(id_paciente)
);

CREATE TABLE paciente_medicamento (
    id_paciente INTEGER NOT NULL,
    medicamento_actual VARCHAR(100) NOT NULL,
    PRIMARY KEY (id_paciente, medicamento_actual),
    FOREIGN KEY (id_paciente) REFERENCES pacientes(id_paciente)
);
--Relaciones N:M
CREATE TABLE paciente_terapeuta (
    id_paciente INTEGER NOT NULL,
    id_terapeuta INTEGER NOT NULL,
    PRIMARY KEY (id_paciente, id_terapeuta),
    FOREIGN KEY (id_paciente) REFERENCES pacientes(id_paciente),
    FOREIGN KEY (id_terapeuta) REFERENCES terapeutas(id_terapeuta)
);

CREATE TABLE paciente_sesion (
    id_paciente INTEGER NOT NULL,
    id_sesion INTEGER NOT NULL,
    PRIMARY KEY (id_paciente, id_sesion),
    FOREIGN KEY (id_paciente) REFERENCES pacientes(id_paciente),
    FOREIGN KEY (id_sesion) REFERENCES sesiones(id_sesion)
);

CREATE TABLE terapeuta_sesion (
    id_terapeuta INTEGER NOT NULL,
    id_sesion INTEGER NOT NULL,
    PRIMARY KEY (id_terapeuta, id_sesion),
    FOREIGN KEY (id_terapeuta) REFERENCES terapeutas(id_terapeuta),
    FOREIGN KEY (id_sesion) REFERENCES sesiones(id_sesion)
);

CREATE TABLE paciente_evaluacion (
    id_paciente INTEGER NOT NULL,
    id_evaluacion INTEGER NOT NULL,
    PRIMARY KEY (id_paciente, id_evaluacion),
    FOREIGN KEY (id_paciente) REFERENCES pacientes(id_paciente),
    FOREIGN KEY (id_evaluacion) REFERENCES evaluaciones_progreso(id_evaluacion)
);

CREATE TABLE evaluacion_terapeuta (
    id_evaluacion INTEGER NOT NULL,
    id_terapeuta INTEGER NOT NULL,
    PRIMARY KEY (id_evaluacion, id_terapeuta),
    FOREIGN KEY (id_evaluacion) REFERENCES evaluaciones_progreso(id_evaluacion),
    FOREIGN KEY (id_terapeuta) REFERENCES terapeutas(id_terapeuta)
);

CREATE TABLE sesion_ejercicio (
    id_sesion INTEGER NOT NULL,
    id_ejercicio INTEGER NOT NULL,
    PRIMARY KEY (id_sesion, id_ejercicio),
    FOREIGN KEY (id_sesion) REFERENCES sesiones(id_sesion),
    FOREIGN KEY (id_ejercicio) REFERENCES ejercicios(id_ejercicio)
);
-- Detalle de ejecucion
CREATE TABLE ejercicio_sesion_detalles (
    id_sesion INTEGER NOT NULL,
    id_ejercicio INTEGER NOT NULL,
    repeticiones INTEGER NOT NULL CHECK (repeticiones > 0),
    duracion INTEGER NOT NULL CHECK (duracion > 0),
    observaciones TEXT,
    PRIMARY KEY (id_sesion, id_ejercicio),
    FOREIGN KEY (id_sesion) REFERENCES sesiones(id_sesion),
    FOREIGN KEY (id_ejercicio) REFERENCES ejercicios(id_ejercicio)
);
-- IOT eventos
CREATE TABLE asistencias_nfc (
    id_asistencia INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_paciente INTEGER NOT NULL,
    id_sesion INTEGER NOT NULL,
    fecha DATE NOT NULL,
    hora_entrada TIME NOT NULL,
    asistencia_confirmada BOOLEAN NOT NULL,
    id_dispositivo INTEGER NOT NULL,
    FOREIGN KEY (id_paciente) REFERENCES pacientes(id_paciente),
    FOREIGN KEY (id_sesion) REFERENCES sesiones(id_sesion),
    FOREIGN KEY (id_dispositivo) REFERENCES dispositivos_nfc(id_dispositivo)
);

CREATE TABLE beacon_evento (
    id_evento INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_beacon INTEGER NOT NULL,
    id_paciente INTEGER NOT NULL,
    fecha DATE NOT NULL,
    hora TIME NOT NULL,
    FOREIGN KEY (id_beacon) REFERENCES beacons(id_beacon),
    FOREIGN KEY (id_paciente) REFERENCES pacientes(id_paciente)
);

CREATE TABLE gps_registros (
    id_registro INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_paciente INTEGER NOT NULL,
    id_terapeuta INTEGER NOT NULL,
    latitud NUMERIC(9,6) NOT NULL CHECK (latitud BETWEEN -90 AND 90),
    longitud NUMERIC(9,6) NOT NULL CHECK (longitud BETWEEN -180 AND 180),
    fecha DATE NOT NULL,
    hora TIME NOT NULL,
    estado VARCHAR(20) NOT NULL,
    FOREIGN KEY (id_paciente) REFERENCES pacientes(id_paciente),
    FOREIGN KEY (id_terapeuta) REFERENCES terapeutas(id_terapeuta)
);

CREATE TABLE gps_vehiculo (
    id_registro INTEGER NOT NULL,
    id_vehiculo INTEGER NOT NULL,
    PRIMARY KEY (id_registro, id_vehiculo),
    FOREIGN KEY (id_registro) REFERENCES gps_registros(id_registro),
    FOREIGN KEY (id_vehiculo) REFERENCES vehiculos(id_vehiculo)
);
-- Índices estrategicos
CREATE INDEX idx_asistencia_paciente ON asistencias_nfc(id_paciente);
CREATE INDEX idx_sesiones_fecha ON sesiones(fecha DESC);
CREATE INDEX idx_gps_fecha ON gps_registros(fecha DESC);
CREATE INDEX idx_beacon_paciente ON beacon_evento(id_paciente);
CREATE INDEX idx_evaluaciones_fecha ON evaluaciones_progreso(fecha DESC);